### ISSUE TITLE
Add the ability to include/exlude certain lights

### ISSUE THREAD

**Issue by stefanwichmann** [stefanwichmann/kelvin#1]
A user an reddit suggested to allow the explicit inclusion or exclusion of certain lights in Kelvin:

`https://de.reddit.com/r/Hue/comments/625of1/meet_kelvin_a_little_bot_i_wrote_to_automate_your/dfjyiyk/`

I think this a a good idea. Right now all capable lights will be managed by Kelvin.

In my opinion it should by sufficient to focus on the exclusion in a first step. In my assumption the average user has 3 - 10 lights in his/her house. In this case it seems reasonable to add the exclusion once and keep the configuration file simple.

Any thoughts?

**Comment by se99jmk** [comment]
Is it better to EXCLUDE specific lights, or INCLUDE specific lights?
Could it alternatively be managed by Room (i.e. groups of lights)?

**Comment by stefanwichmann** [comment]
After thinking about this it should not matter if we define an exlude or include. There will always be cases where the oposite choice might be better suited. So I will go with excludes for now.

Regarding you second question: Right now Kelvin doesn't know any groups or rooms. All lights will be treated equal. Do you see a need to configure different times for different rooms?

**Comment by se99jmk** [comment]
Mmm, I thought about having different settings in the bedroom vs. the living room for example, but may have to use 2x Rasberry Pis?

I was more thinking of the include / exclude, ability to do it by group/room rather than per bulb (as more than likely it's a room of bulbs I'd want to exclude, such as the Bedroom)

**Comment by stefanwichmann** [comment]
I think you really have a point here. I also think a complete and solid room/group concept would be used for more than exluding rooms. I opened issue #4 to discuss this.

Regarding the simple exclusion of idividual lights, I pushed an iniital implementation to the [ignore-lights branch](https://github.com/stefanwichmann/kelvin/tree/ignore-lights). Initial testing looks good.

If you like, give it a try and let me know what you think!

**Comment by stefanwichmann** [comment]
Oh, I missed your first question: Yes, you could use a second Pi if you want to configure two seperate rooms (with their own schedule, colors and brightness). But you could also run **two instances** of Kelvin on **one** Pi. Just use diffent folders:
```
kelvin_livingroom/
  kelvin
  config.json
kelvin_bedroom/
  kelvin
  config.json
```
Both instances can now be run side by side. There are two things you should bear in mind:

1) Make sure to exclude the lights of other instances (otherwise Kelvin will detect a "manual" change)
2) Don't start the local bridge discovery in parallel. For this you will need the same port on your host. Just get the first instance running and once it's up start the second one.
