### ISSUE TITLE
After the Upgrade to v1.3.3, Kelvin No Longer Reacts to Lights Turning On

### ISSUE THREAD

**Issue by porada** [stefanwichmann/kelvin#100]
I’m running Kelvin on Raspberry Pi. Logs suggest proper startup, but no other action seems to happen afterwards.

**Comment by stefanwichmann** [comment]
Sorry to hear that. Could you please update to v1.3.4 and start kelvin with debug logging enabled (./kelvin -deburg)? This should give us some pointers where to look

**Comment by porada** [comment]
Hey Stefan, thanks for the response.

After a manual upgrade from 1.3.3 to 1.3.4 (ARM 64), I get the following error while trying to run Kelvin:

```
exec: Exec format error
The file './kelvin' is marked as an executable but could not be run by the operating system.
```

**Comment by stefanwichmann** [comment]
Looks like you accidentally picked the wrong binary for the raspberry. Try this one:

https://github.com/stefanwichmann/kelvin/releases/download/v1.3.4/kelvin_1.3.4_linux_armv5.tar.gz

**Comment by porada** [comment]
Oh, you’re right. Looks like to the manual upgrade to the _proper_ 1.3.4 build indeed fixed the issue. Not sure why the auto-update hadn’t kicked in, though.

Thanks for the support!
