### ISSUE TITLE
Warmer in the evening?

### ISSUE THREAD

**Issue by se99jmk** [stefanwichmann/kelvin#11]
Hi - I'd like to make the bulbs warmer in the evening, but wasn't 100% sure how to go about this.. 
I can see from the config file there is a setting for AfterSunset, though I don't know what the time value is for.

Can I just choose a brightness and colour temp for AfterSunset, without setting a time, and have Kelvin automatically gradually shift to that temperature in the evening?

By the same token, perhaps something more 'energising' in the morning?

**Comment by stefanwichmann** [comment]
Hi, sure you can do this. Actually it's what Kelvin is supposed to do.

The logic works as follows:
- Between sunrise and sunset Kelvin will use the values defined in the `defaultColortemperature` and `defaultBrightness`. You should set them to a suitable default for when you are awake.
- Between sunset and Midnight Kelvin will schedule through all sets configured in the `AfterSunset`-Section. Depending on your definition of evening you could say: Beginning at 20:00 give me a colortemperature of 2300 kelvin and after 22:00 it should be 2000 kelvin. BTW: This is the default Kelvin generates on the first start.
- Between Midnight and sunrise Kelvin will schedule through all sets configured in the `BeforeSunrise`-Section. To get an energising morning light you can say: After 5:00 give me colortemperature 2900 kelvin.

Hope this helps?!?
