### ISSUE TITLE
Previous versions were deleted from Docker Hub

### ISSUE THREAD

**Issue by billyjanitsch** [stefanwichmann/kelvin#115]
Hi, thank you for your recent updates to the project! Following up on https://github.com/stefanwichmann/kelvin/issues/102, it looks like the latest version (1.3.5) has now been pushed to Docker Hub, but all prior version tags have been deleted. Is it possible to restore them?

**Comment by stefanwichmann** [comment]
Previously to this release every update was only shipped under the "latest" tag and not additionally with an explicit version. So technically every previous version was always deleted with every update... until now
