### ISSUE TITLE
Add ability to have kelvin turn off a light during a schedule

### ISSUE THREAD

**Issue by johnboyle87** [stefanwichmann/kelvin#13]
I love Kelvin! However, I have a few lights in my living room I'd like to be able to just turn off at certain times. Right now the best I can do is set them to a brightness of 1. Thanks!!

**Comment by stefanwichmann** [comment]
Hi,
this sounds like a reasonable request. We would have to change the semantics of the configuration file though and provide a migration for existing ones.

I suppose we could change the "ignore value" from 0 to -1 to allow 0 as an valid brightness value which will turn the light off (the minimum allowed value for brightness is actually 1).

One potential pitfall might be automatically switching off users lights for the first time but never turning them on automatically... what do you think?

**Comment by johnboyle87** [comment]
> I suppose we could change the "ignore value" from 0 to -1 to allow 0 as an valid brightness value which will turn the light off (the minimum allowed value for brightness is actually 1).

I think this would work!

> One potential pitfall might be automatically switching off users lights for the first time but never turning them on automatically... what do you think?

I hadn't thought of that... I think that this is okay though, so long as it's put in the documentation that once a light goes off Kelvin stops controlling it until it is turned back on. At least for me, this would be intended. I have tons of lights in one room and I love how Kelvin dims them as the night moves on, but to get the room even dimmer I'd like for some to turn off. Although I can't imagine a scenario when I would want this function, it could be rectified by including a feature similar to alarms in the standard hue app, where you program lights to turn on at a certain time.

**Comment by stefanwichmann** [comment]
Alright, sound good to me. 

I'm quite busy right now, but will try to give it a shoot in the next few days.

**Comment by stefanwichmann** [comment]
Just pushed a fix for the issue to master. I will test the new functionality over the next few days in my house. If it works as expected I will publish a new release.

Give it a try if you like!

**Comment by stefanwichmann** [comment]
Fixed in version 1.0.4
