### ISSUE TITLE
Light switches for this system

### ISSUE THREAD

**Issue by gedw99** [stefanwichmann/kelvin#15]
Do you know of any powerless & wireless wall light switches by any chance. I want to still be able to activate the lights using wall switches as well as from an app

**Comment by stefanwichmann** [comment]
Hi gedw99,

Kelvin does not make any assumptions about the light switches at all. This means you can choose any switch you want:

- Classic wall mounted switches of any type
- Smart switches from the Philips Hue System
- Or any compatible Hue app

If I get your questions right the following products might be interesting for you:

http://www2.meethue.com/en-us/p/hue-dimmer-switch/046677473372
http://www2.meethue.com/en-us/p/hue-tap-switch/046677473365

Both are wireless, operate without a battery and work fine with Kelvin.

Hope this helps!?!

**Comment by gedw99** [comment]
i think i found something better last nigth


Lights & Power outlets
Sonoff hardware light switches
Mqtt tasmoto code: https://github.com/arendst/Sonoff-Tasmota
Server: https://github.com/pdf/golifx
Upload firmware: https://github.com/arendst/Sonoff-Tasmota/wiki/Upload
No hardware soldering needed !

mqtt all the way...

what do you think ?

**Comment by gedw99** [comment]
they also sell RGB LED
http://sonoff.itead.cc/en/products/residential/sonoff-b1

**Comment by stefanwichmann** [comment]
First of all: Sonoff does not seem to integrate with Philips Hue at all. So Kelvin won't be able to control these switches or the LED bulb at all!

Aside from this the whole systems seem a good fit if you want to control some dumb lightbulbs via app or smart switch. With Philips Hue the focus is definitely on the lightbulbs and less on the switching side of things.

In the end it depends on your needs and taste I guess...

**Comment by gedw99** [comment]
No it's because it supports mqtt so you can standup a raspberry pi as you
mqtt server and you can control hue lights, all power outlets you name it.

The mqtt bit is the interoperability

Also the firmware is ota upgradable to the devices. It's pretty exciting
because there has never been an affordable interoperating solution.

Am not wanting to say do it. Just my own spin on it. I am a systems
architect type.
