### ISSUE TITLE
Docker Timezone

### ISSUE THREAD

**Issue by AdamPan** [stefanwichmann/kelvin#16]
It sems like the docker version doesn’t support the TZ variable, and defaults to UTC. As a reslut, all of the scheduling is thrown off.

**Comment by stefanwichmann** [comment]
Hi Adam,

thanks for reporting this error!

Indeed the timezone database was missing inside the docker image. I fixed this in the master branch and my initial tests showed the right times.

Feel free to test the changes by building an images with the latest Dockerfile and running your container with the parameter "-e TZ=Europe/Berlin" (replace with your timezone).

I will release a new release in the next few days containing this fix.

**Comment by stefanwichmann** [comment]
Fixed in version 1.0.4
