### ISSUE TITLE
Lights switching straight back off after turning on

### ISSUE THREAD

**Issue by Kallb123** [stefanwichmann/kelvin#17]
Got home from holiday to find I couldn't turn any lights on!

I didn't have time to sort it yesterday but I've figured it out today. Kelvin auto updated whilst we were away (yesterday afternoon) and the latest update includes a significant change.

I have Kelvin just controlling colour temperature, so my brightness values were all set to 0 to ignore. This will now turn the light off and a new value of -1 should be used. 

I suggest the updater could migrate these settings? I suppose I have now learned to turn auto update off.

**Comment by stefanwichmann** [comment]
Oops, you are right. Sorry for this!

This was a breaking change that should have resulted in a new major version. The auto update won't upgrade to these to prevent problems like this!

I like the idea of an intelligent migration of the settings after an update!

**Comment by stefanwichmann** [comment]
I just release Kelvin 1.1.0 with a greatly improved configuration migration. Errors like this one should not happen anymore. Enjoy!
