### ISSUE TITLE
Light state has been changed manually.

### ISSUE THREAD

**Issue by jherrick4520** [stefanwichmann/kelvin#20]
I keep getting this messsage:

Light state has been changed manually. Disabling Kelvin...

As far as I can tell I have nothing that is manually changing these light settings.

My setup is just a Phillips hue hub.  I have turned off the device with the hue app, and still get these errors.  No schedules, timers, or motion sensors are configured.

**Comment by stefanwichmann** [comment]
Hi,

try starting Kelvin with the parameter "--debug" to enable additional logging. This way Kelvin will print out the expected and actual state. Maybe this will help us to identify the problem.

Additionally it might be useful to update your lights and bridge software to the latest version (via the hue app) and to identify the model and version number of the light bulb that has this issue.

**Comment by bryanmahler** [comment]
This may or may not be related to your issue, but I was getting similar messages with Hue White Ambiance bulbs when I set them to 2000K. Hue White Ambiance Bulbs support color temperatures 2200-6500K. Setting them to 2000K triggered the "Light state has been changed manually" message on the next polling. Changing the temp setting in the config to 2200K fixed the issue.

**Comment by stefanwichmann** [comment]
This seems to be a different or at least more specific problem. I created #26 for this.

Thanks for reporting!

**Comment by stefanwichmann** [comment]
Closing the issue as it should be fixed with version 1.1.2 of Kelvin.
