### ISSUE TITLE
Unknown color mode in HasChanged method

### ISSUE THREAD

**Issue by Kallb123** [stefanwichmann/kelvin#21]
I'm seeing the following appear in my log every second:

`level=warning msg="💡 HueLight Side Door - Unknown color mode in HasChanged method! Current light state: &{Name:Side Door HueLight:{Id:4 Name:Side Door bridge:0xxxxxx} SetColorTemperature:2000 SetBrightness:-1 TargetColorTemperature:500 TargetColor:[0.527 0.404] TargetBrightness:-1 CurrentColorTemperature:0 CurrentColor:[] CurrentBrightness:254 CurrentColorMode: SupportsColorTemperature:false SupportsXYColor:false Dimmable:true On:true}"`

It only applies to a single bulb, which is on a timer to come on at night and off in the day. Not causing a problem other than filling up the log.

**Comment by stefanwichmann** [comment]
Hi @Kallb123,

thanks for reporting this. The message you see was just introduced for debug purposes and does no harm. But it definitely should not flood your log!

Issue is fixed and I will push an update later today.
