### ISSUE TITLE
Add systemd instructions?

### ISSUE THREAD

**Issue by FezVrasta** [stefanwichmann/kelvin#22]
I know it's trivial but it would be useful to mention how to create a systemd service for this program.

```
# /etc/systemd/system/kelvin.service

[Unit]
Description=Kelvin
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory=/home/pi/Kelvin
ExecStart=/home/pi/Kelvin/kelvin
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

```
$ sudo systemctl enable kelvin
$ sudo systemctl start kelvin
```

**Comment by stefanwichmann** [comment]
Good idea!

I think we could create a folder "etc" and place your sample configuration in a file named "kelvin.service" there. This way people can simple copy this file on their machines and maybe adjust it to their needs.

We also should mention this in the README and include the new folder in each distribution.

PRs are very welcome. ;-)
