### ISSUE TITLE
Allow Relative Offset Times in Schedules

### ISSUE THREAD

**Issue by bryanmahler** [stefanwichmann/kelvin#24]
Since sunrise and sunset times change throughout the year, it would be great to be able to set relative offset times in schedules for beforeSunrise and afterSunset. 

As an example, an afterSunset schedule could include "timeOffset" : "+2:00". If sunset was 6:58, the color and brightness settings would be triggered at 8:58. Later in the year, if sunset was 5:04, it would be triggered at 7:04. beforeSunrise schedules would likely include negative values, though I would find value in negative and positive values for both beforeSunrise and afterSunset. We try to use Kelvin in our home to mimic the circadian rhythm of outdoor light throughout the year.

Thanks! Great bot!

**Comment by stefanwichmann** [comment]
Please see issue #27
