### ISSUE TITLE
Does Kelvin reverts Hue 💡its last settings after hardware light switch is toggled 🔲

### ISSUE THREAD

**Issue by jmgarnier** [stefanwichmann/kelvin#28]
Hallo Stefan,

First, thank you very much for open sourcing this project. It looks very impressive and well documented:) You should add a button for donations and find a way to monetize long term 😉.

I am also of father of toddlers and I bought "White ambiance" Hue for having warmer temperatures in the evening. I did lots of reading before falling to me geeky instincts but so far I am not 💯 % happy with them. My main concern is that as soon as me or my kids use the old school light switch to power off the lights, the smart bulbs forget about their last settings and default light is very bright & cold. Are you supposed to buy motion sensors and Dimmer switches for each room?
![image](https://user-images.githubusercontent.com/8051/36094633-562470ae-0fef-11e8-99e8-41c102e6ef7f.png)

Being a ruby developer, I did some digging and came across your [post in Reddit](https://www.reddit.com/r/Hue/comments/7w5xkp/colortemperature_matched_to_time_of_day/dtxu7me/?st=jdk4qm2r&sh=5a647d9f). Would `kelvin` sort that problem? It looks like it would, even if polling / randomness would add some waiting time & unstability.

I am not sure what to do and I am very tempted to ask for a refund ... There is also some announcement by Phillips that they will fix the startup color.

In https://ioshacker.com/accessories-i/philips-hue-soon-let-set-default-startup-color
> For example, it is unclear if this new option would allow the bulb to revert to its last setting or only one fixed setting set by the user

**Comment by stefanwichmann** [comment]
Hi Jean-Michel,

thanks for your kind words and for your question.

Your situation is exactly what Kelvin was build for. I use old school light switches too and was annoyed by the bright default light. Kelvin will detect every light you switch on (via any type of switch) and will set the color state to whatever you configured it to. So yes, it should solve your problem. Give it a try while your refund period lasts...

Regarding the default startup color: People have been waiting and asking for this for years. Until now Philips said it was a legal issue that prevented them from realizing this. Maybe something has changed here or they found another solution. We'll have to wait and see.

Oh, and there is actually a donation button on top of the readme. ;-)

Enjoy Kelvin and let me know what you think!
