### ISSUE TITLE
Kelvin thinks light is constantly being turned off and on again

### ISSUE THREAD

**Issue by cawith** [stefanwichmann/kelvin#33]
Hi again,

I discovered that some of my lights sometimes are in a constant loop state of being turned on and off according to Kelvin, even though the lights them selves are on all the time.

> time="2018/01/04 10:40:15" level=info msg="💡 Light Entré - Light just appeared."
> time="2018/01/04 10:40:15" level=info msg="💡 Light Entré - Initializing state to 2750K at 100% brightness."
> time="2018/01/04 11:55:04" level=info msg="💡 Light Entré - Light was turned off. Clearing state..."
> time="2018/01/04 11:55:33" level=info msg="💡 Light Entré - Light just appeared."
> time="2018/01/04 11:55:33" level=info msg="💡 Light Entré - Initializing state to 2750K at 100% brightness."
> time="2018/01/04 12:18:11" level=info msg="💡 Light Entré - Light was turned off. Clearing state..."
> time="2018/01/04 12:18:25" level=info msg="💡 Light Entré - Light just appeared."
> time="2018/01/04 12:18:25" level=info msg="💡 Light Entré - Initializing state to 2750K at 100% brightness."
> time="2018/01/04 12:23:10" level=info msg="💡 Light Entré - Light was turned off. Clearing state..."
> time="2018/01/04 12:23:16" level=info msg="💡 Light Entré - Light just appeared."
> time="2018/01/04 12:23:16" level=info msg="💡 Light Entré - Initializing state to 2750K at 100% brightness."
> time="2018/01/04 12:24:59" level=info msg="💡 Light Entré - Light was turned off. Clearing state..."
> time="2018/01/04 12:25:31" level=info msg="💡 Light Entré - Light just appeared."
> time="2018/01/04 12:25:31" level=info msg="💡 Light Entré - Initializing state to 2750K at 100% brightness."
> time="2018/01/04 12:38:18" level=info msg="Looking for updates..."
> time="2018/01/04 12:38:19" level=warning msg="Error looking for update: Invalid Semantic Version"

Same thing happened to two other lights yesterday evening. I made it stop by turning off the light and on again using another scene. Don't know if the scene change was necessary.

Also as you can see at the end, the update feature isn't working in the Docker container.

**Comment by stefanwichmann** [comment]
Same issue as #31 ?
