### ISSUE TITLE
Changing schedule on Kelvin web interface causes "enableWhenLightsAppear" boolean to be reset to false

### ISSUE THREAD

**Issue by Abushawish** [stefanwichmann/kelvin#36]
I know the web interface is in beta, but wanted to give feedback.

**Version:**
Kelvin v1.1.6 running on a Raspberry Pi 3

**Prerequisites:**
1) Web interface in Kelvin should be enabled
2) "enableWhenLightsAppear" attribute in config.json should be set to true

**To recreate:**
1) Open web interface of Kelvin and head to schedules tab
2) Change/add something (example: add entry for the morning at 2AM with 2400 temperature and 60% brightness).
3) Hit "Save Schedules" at the bottom
4) Head to "/home/pi/kelvin" and open config.json 
5) Notice the "enableWhenLightsAppear" has been reset to false even though it was true originally 

Please let me know if I am doing something wrong or more info is needed :).

**Comment by stefanwichmann** [comment]
Hi Moe,

thanks for the report! Even if the web interface is in beta any feedback is valuable.

This is definitely a bug. The "enableWhenLightsAppear" option was added to Kelvin after I last updated the web interface code. So every time the browser send a new config, the default for this option is assumed. And the default is false...
