### ISSUE TITLE
freegeoip.net api going away

### ISSUE THREAD

**Issue by m4rkky** [stefanwichmann/kelvin#40]
If you go to https://freegeoip.net/json/ there is a note saying that service is going away 1 July 2018.  They are renaming the service and you need to register to use the new api.  You could probably switch to https://www.geoip-db.com/json/

**Comment by stefanwichmann** [comment]
Hey m4rkky,
thanks for reporting this, I would have missed this otherwise!

I just pushed release v1.1.7. It includes a new geolocation provider.

Enjoy

**Comment by m4rkky** [comment]
Hi Stefan,

No problem.  Caught it just in time.  Hopefully the switchover doesn't
disrupt too many users.

www.geoip-db.com <https://geoip.nekudo.com> was ipv4 only, so I agree
geoip.nekudo.com was a better choice.

Cheers,
 - Mark
