### ISSUE TITLE
Installing Kelvin on headless raspberry pi

### ISSUE THREAD

**Issue by SoerenNorge** [stefanwichmann/kelvin#43]
I just recently bought my first raspberry pi. Put I'm having trouble figuring out how to install it on a headless version of jessie. I've read through your guides but can't seem to wrap my head around it. 

And thank you for providing this neat application!

**Comment by stefanwichmann** [comment]
Hi Soeren,

thanks for your interest in Kelvin. At which step of the installation process (described in the README.MD) are you struggling?

Stefan

**Comment by stefanwichmann** [comment]
Hi Soeren,

as the webinterface is currently in beta, it is disabled by default. If you run kelvin via ```./kelvin -enableWebInterface``` you should be able to access it via ```http://{IP of your Pi}:8080/```.

Stefan
