### ISSUE TITLE
Bug in computation of colour temperature?

### ISSUE THREAD

**Issue by EmilyBjoerk** [stefanwichmann/kelvin#47]
On the line here:
https://github.com/stefanwichmann/kelvin/blob/712f49842b809908d16e66369a63aecfb954cb43/huelight.go#L295

If you pass 6500K the result of the computation will be 153.846153846 which will truncate to 153 due to use of int(). According to [here](http://www.burgestrand.se/hue-api/api/lights/) the range is 500-154. So 6500K mapping to 153 would be out of range
.

**Comment by stefanwichmann** [comment]
Hi Emily,

thanks for reporting this. The official documentation at https://developers.meethue.com/documentation/lights-api (sadly behind a login) states

> connected lights are capable of 153 (6500K) to 500 (2000K).

Kelvin is implemented in regards to this official specification as close as possible.
