### ISSUE TITLE
Kelvin disables lights in its scenes improperly

### ISSUE THREAD

**Issue by zls88** [stefanwichmann/kelvin#50]
I've currently got a switch with three scenes, activated in this order:

1. `kelvin default`
2. Bright
3. Energize

The idea is that Kelvin is the default, but if I need really bright lights for whatever reason, I can do that.

However, I'm having issues: Kelvin seems to update the scene to have the lights turned off at some point after I configure it. So this is what happens:

| press # | expected      | actual        |
|---------|---------------|---------------|
| 1       | on (kelvin)   | off           |
| 2       | on (bright)   | on (bright)   |
| 3       | on (energize) | on (energize) |
| 4       | on (kelvin)   | on (kelvin)   |
| 5       | on (bright)   | on (bright)   |
| 6       | on (energize) | on (energize) |

this is because Kelvin somehow reconfigures the scene to stop turning on the light itself, so the first press doesn't turn the lights on. I can confirm this by editing the scene in the Hue app; it shows that the light being on is no longer part of the scene. If I loop around back to Kelvin all's well since other scenes have turned it on.

**Comment by stefanwichmann** [comment]
New release is out with a fix for this problem.

Let me know if it worked! Enjoy Kelvin!

**Comment by zls88** [comment]
Works like a charm, thank you :)
