### ISSUE TITLE
Some bulbs get turned off at midnight

### ISSUE THREAD

**Issue by porada** [stefanwichmann/kelvin#52]
Some of my bulbs get automatically turned off by Kelvin after midnight, even though brightness is set to `-1` (unmanaged). Tried using `100` to see if `-1` could be the cause, but the issue still persists.

Once that happens, Kelvin doesn’t respect manual changes—the selected lights get turned off again immediately.

**Comment by stefanwichmann** [comment]
Hi Dominik,

the only situation where Kelvin will actively turn off your lights is an entry in the configuration with brightness zero. Did you restart Kelvin after changing the configuration?

Do the lights turn off at the same time every night?

Please try to start Kelvin with the parameter "-debug". This should give us a better understanding what's going on.

**Comment by porada** [comment]
Hey Stefan, thanks for the response.

I’ve been using Kelvin for months now and none of my presets or schedules has ever had brightness set to `0`. Here’s [my config file](https://gist.github.com/porada/ca53829d3b7eda73da42d8a2759b61a6) by the way. I keep it in a repository and judging by the config tweaks I made in the past, this issue has been happening to me since around the version `1.1.6`.

> Did you restart Kelvin after changing the configuration?

Every single time. 🙂

> Do the lights turn off at the same time every night?

Yep, it’s midnight ± 1 minute.

---

I just launched Kelvin with `-debug`  with an new log file and will report back in a few days.

**Comment by porada** [comment]
I also just discovered by that running Kelvin on startup with `-debug` from within the `.service` file doesn’t respect the flag.

```
ExecStart=/home/pi/Projects/home/kelvin/kelvin -debug -log /home/pi/Projects/home/kelvin/kelvin.log
```

Logging works fine though.

**Comment by stefanwichmann** [comment]
I just released Kelvin 1.2.0 which contains many small fixes including one for the problem you described. Please give it a try and let me know if I works for you.

**Comment by porada** [comment]
I will. Thanks for letting me know!

**Comment by porada** [comment]
Seems like there were no glitches last night. Thank you for fixing this.
