### ISSUE TITLE
Switch to YAML format for more user-friendly configuration

### ISSUE THREAD

**Issue by prfalken** [stefanwichmann/kelvin#56]
Hello and thank you for this amazing project, I'm using it at home and it's great !

Would you like to support YAML instead of JSON for your configuration file ?
It's easier to read/modify, less error prone, and code is not far from the json support.
I have a PR ready if you want.

**Comment by stefanwichmann** [comment]
Hi Julien,
thanks for your suggestion and kudos for even providing a PR! That's awesome!

Indeed I agree that YAML is the better format for configuration files and I probably should have used it from the start...

If we switch to YAML now there are a few things to keep in mind:
- Can we provide a migration for existing JSON configuration files? (We should not break existing setups)
- There is some Javascript code in the web UI that also creates and modifies the configuration. Here we have a natural fit for JSON as Javascript can handle it natively. So we either need two representations (JSON and YAML) or need to use YAML serialization in the frontend code.

Until now this added complexity kept me from utilizing the benefits of a configuration in YAML format.

What do you think?

**Comment by prfalken** [comment]
* I thought about it and you're right, I should provide a migration path for existing confs.
* also right, I may have overlooked the UI part as I don't use it.

I'll think about it and suggest solutions for the 2 items.

**Comment by prfalken** [comment]
We could do something like this in the config initialization phase :
```
if filepath.Ext(configuration.ConfigurationFile) == ".json" {
	log.Printf("⚙ Configuration %v is in JSON format, generating yaml equivalent", configuration.ConfigurationFile)
	log.Printf("⚙ Please rename your configuration file to config.yaml to finish migration")
	configuration.Hash = ""
	err := configuration.Write()
}
```
This would write in yaml format in the config.json file.
Users would have to rename their config file to ".yaml", so that config file would not be rewritten again.

In any case in this PR, changing parameters from the web interface would trigger a YAML format write in the config file.

There is one missing issue though : Default configuration flag should stay "config.json" in order not to break users who don't mention any configuration flag. If we want to finally move to YAML, there is going to be a backwards incompatible version of kelvin at some point.

* Another way would be to support both yaml and json depending on the config file's extension.

What do you think ?

**Comment by prfalken** [comment]
as suggested by @npwalker, I'm trying to support both JSON and YAML in a first PR.
In a second pass you will be able to make kelbin create a yaml configuration when none is provided, and update the README accordingly.
