### ISSUE TITLE
General understanding confirmation & question about color.

### ISSUE THREAD

**Issue by GollyJer** [stefanwichmann/kelvin#66]
General understanding question...
---
Hi! Kelvin is exactly what I'm looking for to get my Hue bulbs synced to CF.Lumen on my phones and f.lux on my computer. Thanks for the amazing work!

I took a screenshot of the f.lux app and overlaid how I understand Kelvin works.

![image](https://user-images.githubusercontent.com/689204/58197058-537efc80-7c80-11e9-9cfc-1a315b55f9f2.png)

- The `Daytime` curve is static but the color and temp is user configurable.
- The `Sunset` curve, color, and brightness are automated by Kelvin.
- The `After Sunset` curve, temp, and brightness is user configurable.
- The `Before Sunrise` curve, temp, and brightness is user configurable.

Is this a correct understanding?

Set color question...
---
I'm looking for the simplest way to set the lights red at 10PM but keep Kelvin controlling them when turned back on in the morning. Something like this...

![image](https://user-images.githubusercontent.com/689204/58197999-49f69400-7c82-11e9-9373-80f2aeb7017f.png)

It seems Kelvin can only set temperature. Is that correct? If so, is there a recommended approach? 

Thanks again for the awesome app! 👍😀

Jeremy

**Comment by npwalker** [comment]
@GollyJer If you install and run Kelvin it produces a default config that includes the afterSunset section in the schdules.  

Here's the example from the README.  

```
      "afterSunset": [
        {
          "time": "20:00",
          "colorTemperature": 2300,
          "brightness": 80
        },
        {
          "time": "22:00",
          "colorTemperature": 2000,
          "brightness": 60
        }
      ]
```

You can see that it sets the colorTemperature to 2000 at 10PM and a brightness of 60.  If you have extended color bulbs you can set the colorTemperature to 1000 and they will be red.  

I think kelvin will slowly move your bulbs towards that colorTemperature between the previously scheduled time.  So in the example the colorTemp is 2300 at 8PM.  So it would slow move from 2300 to 2000 over the course of the 2 hours.  

If you want it to stay at one color all the way up until 10PM then you would just set a schedule block for 9:59PM with the same colorTemp ( 2300 in the example case) and then kelvin wouldn't be slowly moving the color.  

Hope that helps.

**Comment by GollyJer** [comment]
Hi @npwalker. Thanks for the help.
Yes. I have installed Kelvin and customized the `config.json`.

1000K is the closest the temperature setting can get to red but it is definitely not red.  I guess, based on your answer, that Kelvin can't set XY color values? Red is X: 0.32 Y:0.33.

**Comment by npwalker** [comment]
The temperatures get translated to x y I think.  I added the ability for color bulbs to go down to 1000k over in this PR.  You can see what the 1000k translates to: 

https://github.com/stefanwichmann/kelvin/pull/59/files#diff-a4d05705c40377c110853572c7051ce8R54

If you wanted you could change that entry to whatever x y you prefer, recompile, and see if that works for you.  As far as I know you cannot set X Y directly in kelvin config.

**Comment by stefanwichmann** [comment]
Hi Jeremy,

thanks for your interest in Kelvin.

Nick's statement is mostly accurate: Kelvin will let you specify the "color" of your lights only as "color temperature" measured in kelvin. The maximum range is from 1000K (warm, red) to 6500K (cold, blue). Depending of your specific model of Hue lights this range might be limited and Kelvin will use the most appropriate technical color mode (ct or xy) internally to set your state.

If 1000K is not red enough you are currently (sadly) out of luck. As the primary job of Kelvin is to mimic the states of sunlight from the outside, I have no plans of going below 1000K.

**Comment by GollyJer** [comment]
@stefanwichmann. Thanks for the definitive answer. And the awesome app. 👍
