### ISSUE TITLE
Override bulb color ability?

### ISSUE THREAD

**Issue by OBoudreaux** [stefanwichmann/kelvin#68]
I currently run a mix of hue white ambiance and some knockoff color strips. For the strips the hue app controls the two white diodes and the color diodes separately. This is great because I can choose the "relax" scene, for example, and all of the lights have the same temperature (more or less). 

Kelvin seems to adjust the light temperature with the color diodes if they are supported by the bulb (strip in this case). The result is that when I choose a default color temperature in kelvin, I end up with a mish mash of light temperatures; the ambient bulbs put out the expected temperature of white while the color strips try to approximate this using the color diodes. At the upper end, the strips seem almost purpleish.

Is there a way to to force kelvin to only use the white channels on the color strips?

**Comment by BindersFullOfWomen** [comment]
Who makes the knockoff color strips?

**Comment by OBoudreaux** [comment]
There are loads of them on AliExpress. The particular controllers I have are sold under the name GLEDOPTO, specifically the RGB+CCT model.

**Comment by stefanwichmann** [comment]
Hi,
Kelvin can only see and use the lights exposed by the Hue bridge.

If they appear there as "two different lights" you can just exclude the color diodes from the configuration.

If they appear as one light you are sadly out of luck...

**Comment by OBoudreaux** [comment]
How would it work with a normal color hue bulb? Would the temperature adjustment be the white diodes or the color diodes? Or it that just left to the bridge to decide?

**Comment by stefanwichmann** [comment]
That is left for bridge to decide and can not be influenced in the API calls from outside the bridge.
