### ISSUE TITLE
arm version segfaulting

### ISSUE THREAD

**Issue by murzz** [stefanwichmann/kelvin#7]
Running Kelvin on arm board, it segfaults. No difference if `config.json` generated on PC is present or not.

Output below:
```
$ ./kelvin
Segmentation fault
$ uname -a
Linux armboard 2.6.32.65-bcm5892-secure #2 PREEMPT Thu Mar 24 16:15:42 CST 2016 armv6l GNU/Linux
```

**Comment by stefanwichmann** [comment]
What kind of board are you running Kelvin on? Doesn't look like an Raspberry Pi...

Did you choose the right binary during download? It should be `linux-arm`.

**Comment by murzz** [comment]
Not a raspberry, just some noname board. Yes, I tried with linux-arm.
Anyway I have tried to build and run go 'hello world' on that board, it also segfaults.
I don't think its Kelvin problem, will close the issue.
