### ISSUE TITLE
Lights don't change throughout the day

### ISSUE THREAD

**Issue by TheBasementNerd** [stefanwichmann/kelvin#73]
I may have just gotten the intent of this app incorrectly, from reading I figured the purpose was that throughout the day the lights it's controlling in a schedule would be gently adjusted to match what the relative light levels outside should be, and provide a match to circadian rhythm. I downloaded this for my hue bulbs in my home office (no windows) so that I'd have a semblance of time without having to check the clock. I'm not sure if they are supposed to be doing that and aren't, or if I'll have to manually define multiple times for them to adjust during the day

**Comment by stefanwichmann** [comment]
Hi David,

you got the idea right. 

What you observed might be the following characteristic of Kelvin: Between sunrise and sunset, your lights will be kept at a constant value. It‘s only the phases around rising and setting sun where you will see changes. 

If you didn’t observe any changes in the stated times, there might be another problem. 

Hope this helps!?!

**Comment by TheBasementNerd** [comment]
Ok thank you, I actually went ahead and coded my own app to fit my needs,
the app did work as you described I just wasn't sure if I was the intent. I
set up one on my own to work as I needed
