### ISSUE TITLE
Add the ability to only control one parameter

### ISSUE THREAD

**Issue by Kallb123** [stefanwichmann/kelvin#8]
I would prefer if kelvin would only change the colour temperature of the bulbs.

**Comment by Kallb123** [comment]
To expand a little, I have many things in the house that control the brightness of the lights, so I would rather leave this to be controlled via existing means. 

For example, my phone alarm turns on my light at a very low brightness. Due to it being after sunrise, Kelvin was turning the brightness right up and giving me a true sunrise in the morning. 

Another example, I have most of my dimmers switches to do "1 press, dim - 2 press, brighter" etc. Kelvin was disturbing the flow of this and making the first press less predictable. 

I would love to have kelvin control the colour temperature, as all my first presses are just normal white.

**Comment by stefanwichmann** [comment]
I see your point and like the idea to make Kelvin more flexible in this regard.

My current take on this would be to allow zero (`0`) or empty (`""`) configuration values for *all* brightness and color temperature values. With this change you would be able to tell Kelvin if and when you would like it to manage either values...

Does this make sense?

**Comment by Kallb123** [comment]
Perfect. I tried to delete the values but they put themselves back on restart. So yes, being able to leave them empty would be ideal. I imagine some people might want to just control brightness, whereas I only want to control temperature.

**Comment by stefanwichmann** [comment]
Just released v0.0.13 with the ability to ignore brightness or color temperature.

Give it a try and enjoy! Let me know if you find problems!
