### ISSUE TITLE
Failed to discover bridge automatically

### ISSUE THREAD

**Issue by flmessier** [stefanwichmann/kelvin#82]
Just tried to setup kelvin on a pi and had to add the IP address of my bridge manually to the config file to get the prompt to press the setup button upon service start. Prior to updating config with the address I would get the following output in the logs:

```time="2020/18/08 03:31:43" level=info msg="🤖 Kelvin v1.3.2 starting up... 🚀"
time="2020/18/08 03:31:43" level=info msg="⚙ Default configuration generated"
time="2020/18/08 03:31:43" level=info msg="🤖 Initializing bridge connection..."
time="2020/18/08 03:31:43" level=info msg="Looking for updates..."
time="2020/18/08 03:31:47" level=error msg="Could not initialze bridge: Bridge discovery failed - Retrying..."
(last message repeats itself)
```

TBH I did not look at the code for the discovery process of the bridge, could be that my Google Wifi mesh network blocks the auto discovery process. 

After updating the config with the IP address of the bridge, got the following output:

```time="2020/18/08 03:37:41" level=info msg="🤖 Kelvin v1.3.2 starting up... 🚀"
time="2020/18/08 03:37:41" level=info msg="⚙ Configuration /opt/kelvin/config.json loaded"
time="2020/18/08 03:37:41" level=info msg="🤖 Initializing bridge connection..."
time="2020/18/08 03:37:41" level=info msg="Looking for updates..."
time="2020/18/08 03:37:41" level=info msg="⌘ Starting user registration."
time="2020/18/08 03:37:41" level=warning msg="⌘ PLEASE PUSH THE BLUE BUTTON ON YOUR HUE BRIDGE"
```

**Comment by mstefany** [comment]
I had exactly the same problem today initializing Kelvin and I also had to input the IP address manually into config.json.

I read the part of the Kelvin code which is supposed to discover the bridge, and it's actually using DiscoverBridges function from https://github.com/stefanwichmann/go.hue which relies on being able to listen on UDP port 1900 - in my case this is occupied by openHAB which runs on the same RPi (with Hue binding, of course).

I don't think there are many options here, maybe only better error message to let the user know that UDP port 1900 is used by something else and discovery won't work.

**Comment by mstefany** [comment]
I had the same problem, and it seems, at least in my case that the discovery fails because UDP port 1900 is used by something else (openHAB with Hue binding in my case). That's for the first part of the discovery process (UPnP way), why it was not found by second stage full network scan I don't know.

**Comment by stefanwichmann** [comment]
Philips broke discovery a while back. Fixed now
