### ISSUE TITLE
Build version for routers / OpenWrt

### ISSUE THREAD

**Issue by PetrVys** [stefanwichmann/kelvin#86]
Hello,

Kelvin successfully runs on OpenWrt (and other linux based routers) since Go compiles to static binaries, but it is not currently compiled for most used router architectures. Binary size is a potential issue, but there are a lot of routers that can host 12MB binary easily (e.g. with the binary on USB).

Please add release binaries for routers:
arm64 - recent powerful routers, newer Raspbery PIs - build with parameters: `GOARCH=arm64 GOOS=linux`
mips softfloat - older but still sold Atheros or Broadcom routers (AR71xx, BCM41xx etc.) - build with parameters: `GOOS=linux GOARCH=mips GOMIPS=softfloat`

Additionally, routers do not have systemd, so add instructions in README.md - add to /etc/rc.local:  
`cd /opt/kelvin`
`./kelvin &`

**Comment by stefanwichmann** [comment]
Added to the build script, will be part of the next release
