### ISSUE TITLE
Finding Devices ID when running as service

### ISSUE THREAD

**Issue by er-minio** [stefanwichmann/kelvin#88]
I've been running Kelvin for a few years as a service on a Raspberry pi Zero W, all good, love it.

I now changed my light configuration and I really have to get Kelvin to ignore one of the lights, but I cannot find its ID as I'm not able to see Kelvin's status when it is first initiated.

When  I do sudo systemctl status kelvin, I only get the lights by name, no ID.
Is there any other way to obtain the table of ID/Light names?

Or, is there an easy way to tell Kelvin to ignore a specific light?

Thanks.
![Screenshot 2021-01-28 at 14 18 10](https://user-images.githubusercontent.com/89927/106150918-b8883680-6173-11eb-9fcc-931a3cbfc586.png)
![Screenshot 2021-01-28 at 14 18 29](https://user-images.githubusercontent.com/89927/106150928-ba51fa00-6173-11eb-9beb-cf1ed06aee6d.png)

**Comment by stefanwichmann** [comment]
Your log output of journalctl was truncated/paged and does not show all available lines. 

Try calling it with the parameter "--no-tail". This should give you the table where you can find the ID of each lamp. 

After you identified the lamp you want to ignore, simply remove its ID from the configuration file.

**Comment by er-minio** [comment]
Thank you Stefan!
