### ISSUE TITLE
Kelvin not allowing manual color changes

### ISSUE THREAD

**Issue by turtle2626** [stefanwichmann/kelvin#92]
Hi! Hope all is well.

I’ve run into an issue that prevents me from manually making color changes to my philips hue lights. Each time I try to adjust the color using the color picker, kelvin will automatically change it back to the bright white setting I have for the daytime. Oddly enough, this issue does not happen when I change the white temperature using the white shade picker. Kelvin recognizes I have made a manual change and reacts appropriately. Kelvin also lets me make manual changes when I activate a scene. I appreciate the help!

**Comment by RaphaelMarinier** [comment]
I sent a [pull request](https://github.com/stefanwichmann/kelvin/pull/91) to fix this, but unfortunately, it has not been accepted yet.
If you want the fix, you can clone and build kelvin from [my branch](https://github.com/RaphaelMarinier/kelvin/tree/equals_float_bugfix).

**Comment by er-minio** [comment]
I'm having a similar issue.

I'm able to override Kelvin with this procedure:

1. Set a different white temperature for the light. Kelvin will accept the override.
2. Set the lights to a different colour.

This works on both my Signe lamps. My Bloom light instead keeps getting overridden. Hue app behaviour for the Bloom light is glitchy: you cannot switch properly between the colour and white temp selector.

**Comment by stefanwichmann** [comment]
I finally found the time to fix the release pipeline and merged the fix from @RaphaelMarinier. Will issue a new release with this to hopefully resolve the issue

**Comment by stefanwichmann** [comment]
Fixed with release v.1.3.4
