### ISSUE TITLE
Down for me or everyone?

### ISSUE THREAD

**Issue by GollyJer** [stefanwichmann/kelvin#96]
Hey! I'm not sure if it's a local network change that is causing my issue or if it's the updates recently pushed by Hue to the bridges.

Is anyone else getting this issue when setting up a fresh install of Kelvin?
![image](https://user-images.githubusercontent.com/689204/143663189-562417bf-e32c-442f-b0c0-a2b9e3bf9cd4.png)

I had it running for a couple years without issue. Thanks!

**Comment by stefanwichmann** [comment]
Hey Jeremy,
it works just fine on my end. You could use the Hue app to verify that you are using the right IP address to connect, especially after changes to your local network.

**Comment by GollyJer** [comment]
Hey @stefanwichmann. Thanks for the reply.

This is during the initial setup with a fresh folder of `kelvin-windows-amd64-v1.3.2` on my desktop.
If I remember correctly doesn't kelvin find the hub and ask me to press the button?

**Comment by GollyJer** [comment]
Figured out my device ip addresses and coded them in myself. Everything started working again. I'm not sure why bridge-discovery isn't working but setting the ip addresses in the config by hand did work. Thanks.
