### ISSUE TITLE
Auto update installed bad binary on Raspberry Pi

### ISSUE THREAD

**Issue by ItsHoff** [stefanwichmann/kelvin#98]
Hey, 

last night Kelvin downloaded the new update, but the newly installed binary did not work on my Raspberry Pi (3B iirc). The installed binary was giving me "Exec format error". I checked the logs and noticed Kelvin had installed the package https://github.com/stefanwichmann/kelvin/releases/download/v1.3.3/kelvin_1.3.3_linux_arm64.tar.gz. Not sure if that package should work on Raspberry Pi or if there is something wrong with the package.

I manually installed the https://github.com/stefanwichmann/kelvin/releases/download/v1.3.3/kelvin_1.3.3_linux_armv5.tar.gz package and that one works.

In any case, thanks for your work on this great project!

**Comment by slunnnko** [comment]
Thnx, that workaround saved my day :).

**Comment by stefanwichmann** [comment]
Damn, that is a fallout from the new release procedure. Sorry about that. Looking into it

**Comment by stefanwichmann** [comment]
Fixed with release v1.3.4 by disabling arm64 builds for now.
